server:
  port: 8084
spring:
  r2dbc:
    url: r2dbc:postgresql:/94.198.218.71:5434/personeservice
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://94.198.218.71:5434/personeservice
    locations: classpath:db/migration
    user: postgres
    password: postgres
