server:
  port: 8084
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/personservice
    username: postgres
    password: 4
  flyway:
    url: jdbc:postgresql://localhost:5432/personservice
    locations: filesystem:src/main/resources/db/migration
    user: postgres
    password: 4
