server:
  port: 8090
spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/personeservice
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://postgres:5432/personeservice
    locations: classpath:db/migration
    user: postgres
    password: postgres
