INSERT INTO countries (name, alpha2, alpha3, status)
VALUES ('Afghanistan', 'AF', 'AFG', 'ACTIVE'),
       ('Albania', 'AL', 'ALB', 'ACTIVE'),
       ('Algeria', 'DZ', 'DZA', 'ACTIVE'),
       ('Andorra', 'AD', 'AND', 'ACTIVE'),
       ('Angola', 'AO', 'AGO', 'ACTIVE'),
       ('Argentina', 'AR', 'ARG', 'ACTIVE'),
       ('Armenia', 'AM', 'ARM', 'ACTIVE'),
       ('Australia', 'AU', 'AUS', 'ACTIVE'),
       ('Austria', 'AT', 'AUT', 'ACTIVE'),
       ('Azerbaijan', 'AZ', 'AZE', 'ACTIVE'),
       ('Bahamas', 'BS', 'BHS', 'ACTIVE'),
       ('Bahrain', 'BH', 'BHR', 'ACTIVE'),
       ('Bangladesh', 'BD', 'BGD', 'ACTIVE'),
       ('Barbados', 'BB', 'BRB', 'ACTIVE'),
       ('Belarus', 'BY', 'BLR', 'ACTIVE'),
       ('Belgium', 'BE', 'BEL', 'ACTIVE'),
       ('Belize', 'BZ', 'BLZ', 'ACTIVE'),
       ('Benin', 'BJ', 'BEN', 'ACTIVE'),
       ('Bhutan', 'BT', 'BTN', 'ACTIVE'),
       ('Bolivia', 'BO', 'BOL', 'ACTIVE'),
       ('Bosnia and Herzegovina', 'BA', 'BIH', 'ACTIVE'),
       ('Botswana', 'BW', 'BWA', 'ACTIVE'),
       ('Brazil', 'BR', 'BRA', 'ACTIVE'),
       ('Brunei', 'BN', 'BRN', 'ACTIVE'),
       ('Bulgaria', 'BG', 'BGR', 'ACTIVE'),
       ('Burkina Faso', 'BF', 'BFA', 'ACTIVE'),
       ('Burundi', 'BI', 'BDI', 'ACTIVE'),
       ('Cabo Verde', 'CV', 'CPV', 'ACTIVE'),
       ('Cambodia', 'KH', 'KHM', 'ACTIVE'),
       ('Cameroon', 'CM', 'CMR', 'ACTIVE'),
       ('Canada', 'CA', 'CAN', 'ACTIVE'),
       ('Central African Republic', 'CF', 'CAF', 'ACTIVE'),
       ('Chad', 'TD', 'TCD', 'ACTIVE'),
       ('Chile', 'CL', 'CHL', 'ACTIVE'),
       ('China', 'CN', 'CHN', 'ACTIVE'),
       ('Colombia', 'CO', 'COL', 'ACTIVE'),
       ('Comoros', 'KM', 'COM', 'ACTIVE'),
       ('Congo (Congo-Brazzaville)', 'CG', 'COG', 'ACTIVE'),
       ('Congo (Democratic Republic)', 'CD', 'COD', 'ACTIVE'),
       ('Costa Rica', 'CR', 'CRI', 'ACTIVE'),
       ('Croatia', 'HR', 'HRV', 'ACTIVE'),
       ('Cuba', 'CU', 'CUB', 'ACTIVE'),
       ('Cyprus', 'CY', 'CYP', 'ACTIVE'),
       ('Czech Republic', 'CZ', 'CZE', 'ACTIVE'),
       ('Denmark', 'DK', 'DNK', 'ACTIVE'),
       ('Djibouti', 'DJ', 'DJI', 'ACTIVE'),
       ('Dominica', 'DM', 'DMA', 'ACTIVE'),
       ('Dominican Republic', 'DO', 'DOM', 'ACTIVE'),
       ('Ecuador', 'EC', 'ECU', 'ACTIVE'),
       ('Egypt', 'EG', 'EGY', 'ACTIVE'),
       ('El Salvador', 'SV', 'SLV', 'ACTIVE'),
       ('Equatorial Guinea', 'GQ', 'GNQ', 'ACTIVE'),
       ('Eritrea', 'ER', 'ERI', 'ACTIVE'),
       ('Estonia', 'EE', 'EST', 'ACTIVE'),
       ('Eswatini', 'SZ', 'SWZ', 'ACTIVE'),
       ('Ethiopia', 'ET', 'ETH', 'ACTIVE'),
       ('Fiji', 'FJ', 'FJI', 'ACTIVE'),
       ('Finland', 'FI', 'FIN', 'ACTIVE'),
       ('France', 'FR', 'FRA', 'ACTIVE'),
       ('Gabon', 'GA', 'GAB', 'ACTIVE'),
       ('Gambia', 'GM', 'GMB', 'ACTIVE'),
       ('Georgia', 'GE', 'GEO', 'ACTIVE'),
       ('Germany', 'DE', 'DEU', 'ACTIVE'),
       ('Ghana', 'GH', 'GHA', 'ACTIVE'),
       ('Greece', 'GR', 'GRC', 'ACTIVE'),
       ('Grenada', 'GD', 'GRD', 'ACTIVE'),
       ('Guatemala', 'GT', 'GTM', 'ACTIVE'),
       ('Guinea', 'GN', 'GIN', 'ACTIVE'),
       ('Guinea-Bissau', 'GW', 'GNB', 'ACTIVE'),
       ('Guyana', 'GY', 'GUY', 'ACTIVE'),
       ('Haiti', 'HT', 'HTI', 'ACTIVE'),
       ('Honduras', 'HN', 'HND', 'ACTIVE'),
       ('Hungary', 'HU', 'HUN', 'ACTIVE'),
       ('Iceland', 'IS', 'ISL', 'ACTIVE'),
       ('India', 'IN', 'IND', 'ACTIVE'),
       ('Indonesia', 'ID', 'IDN', 'ACTIVE'),
       ('Iran', 'IR', 'IRN', 'ACTIVE'),
       ('Iraq', 'IQ', 'IRQ', 'ACTIVE'),
       ('Ireland', 'IE', 'IRL', 'ACTIVE'),
       ('Israel', 'IL', 'ISR', 'ACTIVE'),
       ('Italy', 'IT', 'ITA', 'ACTIVE'),
       ('Jamaica', 'JM', 'JAM', 'ACTIVE'),
       ('Japan', 'JP', 'JPN', 'ACTIVE'),
       ('Jordan', 'JO', 'JOR', 'ACTIVE'),
       ('Kazakhstan', 'KZ', 'KAZ', 'ACTIVE'),
       ('Kenya', 'KE', 'KEN', 'ACTIVE'),
       ('Kiribati', 'KI', 'KIR', 'ACTIVE'),
       ('Kuwait', 'KW', 'KWT', 'ACTIVE'),
       ('Kyrgyzstan', 'KG', 'KGZ', 'ACTIVE'),
       ('Laos', 'LA', 'LAO', 'ACTIVE'),
       ('Latvia', 'LV', 'LVA', 'ACTIVE'),
       ('Lebanon', 'LB', 'LBN', 'ACTIVE'),
       ('Lesotho', 'LS', 'LSO', 'ACTIVE'),
       ('Liberia', 'LR', 'LBR', 'ACTIVE'),
       ('Libya', 'LY', 'LBY', 'ACTIVE'),
       ('Liechtenstein', 'LI', 'LIE', 'ACTIVE'),
       ('Lithuania', 'LT', 'LTU', 'ACTIVE'),
       ('Luxembourg', 'LU', 'LUX', 'ACTIVE'),
       ('Madagascar', 'MG', 'MDG', 'ACTIVE'),
       ('Malawi', 'MW', 'MWI', 'ACTIVE'),
       ('Malaysia', 'MY', 'MYS', 'ACTIVE'),
       ('Maldives', 'MV', 'MDV', 'ACTIVE'),
       ('Mali', 'ML', 'MLI', 'ACTIVE'),
       ('Malta', 'MT', 'MLT', 'ACTIVE'),
       ('Marshall Islands', 'MH', 'MHL', 'ACTIVE'),
       ('Mauritania', 'MR', 'MRT', 'ACTIVE'),
       ('Mauritius', 'MU', 'MUS', 'ACTIVE'),
       ('Mexico', 'MX', 'MEX', 'ACTIVE'),
       ('Micronesia', 'FM', 'FSM', 'ACTIVE'),
       ('Moldova', 'MD', 'MDA', 'ACTIVE'),
       ('Monaco', 'MC', 'MCO', 'ACTIVE'),
       ('Mongolia', 'MN', 'MNG', 'ACTIVE'),
       ('Montenegro', 'ME', 'MNE', 'ACTIVE'),
       ('Morocco', 'MA', 'MAR', 'ACTIVE'),
       ('Mozambique', 'MZ', 'MOZ', 'ACTIVE'),
       ('Myanmar', 'MM', 'MMR', 'ACTIVE'),
       ('Namibia', 'NA', 'NAM', 'ACTIVE'),
       ('Nauru', 'NR', 'NRU', 'ACTIVE'),
       ('Nepal', 'NP', 'NPL', 'ACTIVE'),
       ('Netherlands', 'NL', 'NLD', 'ACTIVE'),
       ('New Zealand', 'NZ', 'NZL', 'ACTIVE'),
       ('Nicaragua', 'NI', 'NIC', 'ACTIVE'),
       ('Niger', 'NE', 'NER', 'ACTIVE'),
       ('Nigeria', 'NG', 'NGA', 'ACTIVE'),
       ('North Korea', 'KP', 'PRK', 'ACTIVE'),
       ('North Macedonia', 'MK', 'MKD', 'ACTIVE'),
       ('Norway', 'NO', 'NOR', 'ACTIVE'),
       ('Oman', 'OM', 'OMN', 'ACTIVE'),
       ('Pakistan', 'PK', 'PAK', 'ACTIVE'),
       ('Palau', 'PW', 'PLW', 'ACTIVE'),
       ('Panama', 'PA', 'PAN', 'ACTIVE'),
       ('Papua New Guinea', 'PG', 'PNG', 'ACTIVE'),
       ('Paraguay', 'PY', 'PRY', 'ACTIVE'),
       ('Peru', 'PE', 'PER', 'ACTIVE'),
       ('Philippines', 'PH', 'PHL', 'ACTIVE'),
       ('Poland', 'PL', 'POL', 'ACTIVE'),
       ('Portugal', 'PT', 'PRT', 'ACTIVE'),
       ('Qatar', 'QA', 'QAT', 'ACTIVE'),
       ('Romania', 'RO', 'ROU', 'ACTIVE'),
       ('Russia', 'RU', 'RUS', 'ACTIVE'),
       ('Rwanda', 'RW', 'RWA', 'ACTIVE'),
       ('Saint Kitts and Nevis', 'KN', 'KNA', 'ACTIVE'),
       ('Saint Lucia', 'LC', 'LCA', 'ACTIVE'),
       ('Saint Vincent and the Grenadines', 'VC', 'VCT', 'ACTIVE'),
       ('Samoa', 'WS', 'WSM', 'ACTIVE'),
       ('San Marino', 'SM', 'SMR', 'ACTIVE'),
       ('Sao Tome and Principe', 'ST', 'STP', 'ACTIVE'),
       ('Saudi Arabia', 'SA', 'SAU', 'ACTIVE'),
       ('Senegal', 'SN', 'SEN', 'ACTIVE'),
       ('Serbia', 'RS', 'SRB', 'ACTIVE'),
       ('Seychelles', 'SC', 'SYC', 'ACTIVE'),
       ('Sierra Leone', 'SL', 'SLE', 'ACTIVE'),
       ('Singapore', 'SG', 'SGP', 'ACTIVE'),
       ('Slovakia', 'SK', 'SVK', 'ACTIVE'),
       ('Slovenia', 'SI', 'SVN', 'ACTIVE'),
       ('Solomon Islands', 'SB', 'SLB', 'ACTIVE'),
       ('Somalia', 'SO', 'SOM', 'ACTIVE'),
       ('South Africa', 'ZA', 'ZAF', 'ACTIVE'),
       ('South Korea', 'KR', 'KOR', 'ACTIVE'),
       ('South Sudan', 'SS', 'SSD', 'ACTIVE'),
       ('Spain', 'ES', 'ESP', 'ACTIVE'),
       ('Sri Lanka', 'LK', 'LKA', 'ACTIVE'),
       ('Sudan', 'SD', 'SDN', 'ACTIVE'),
       ('Suriname', 'SR', 'SUR', 'ACTIVE'),
       ('Sweden', 'SE', 'SWE', 'ACTIVE'),
       ('Switzerland', 'CH', 'CHE', 'ACTIVE'),
       ('Syria', 'SY', 'SYR', 'ACTIVE'),
       ('Taiwan', 'TW', 'TWN', 'ACTIVE'),
       ('Tajikistan', 'TJ', 'TJK', 'ACTIVE'),
       ('Tanzania', 'TZ', 'TZA', 'ACTIVE'),
       ('Thailand', 'TH', 'THA', 'ACTIVE'),
       ('Timor-Leste', 'TL', 'TLS', 'ACTIVE'),
       ('Togo', 'TG', 'TGO', 'ACTIVE'),
       ('Tonga', 'TO', 'TON', 'ACTIVE'),
       ('Trinidad and Tobago', 'TT', 'TTO', 'ACTIVE'),
       ('Tunisia', 'TN', 'TUN', 'ACTIVE'),
       ('Turkey', 'TR', 'TUR', 'ACTIVE'),
       ('Turkmenistan', 'TM', 'TKM', 'ACTIVE'),
       ('Tuvalu', 'TV', 'TUV', 'ACTIVE'),
       ('Uganda', 'UG', 'UGA', 'ACTIVE'),
       ('Ukraine', 'UA', 'UKR', 'ACTIVE'),
       ('United Arab Emirates', 'AE', 'ARE', 'ACTIVE'),
       ('United Kingdom', 'GB', 'GBR', 'ACTIVE'),
       ('United States', 'US', 'USA', 'ACTIVE'),
       ('Uruguay', 'UY', 'URY', 'ACTIVE'),
       ('Uzbekistan', 'UZ', 'UZB', 'ACTIVE'),
       ('Vanuatu', 'VU', 'VUT', 'ACTIVE'),
       ('Vatican City', 'VA', 'VAT', 'ACTIVE'),
       ('Venezuela', 'VE', 'VEN', 'ACTIVE'),
       ('Vietnam', 'VN', 'VNM', 'ACTIVE'),
       ('Yemen', 'YE', 'YEM', 'ACTIVE'),
       ('Zambia', 'ZM', 'ZMB', 'ACTIVE'),
       ('Zimbabwe', 'ZW', 'ZWE', 'ACTIVE');
